- name: Create DevOps Users
  hosts: all
  become: true
  tasks:
    - name: Create a new user
      user:
        name: devops
        state: present
        shell: /bin/bash

    - name: Add SSH Key for devops user
      authorized_key:
        user: devops
        state: present
        key: "{{ lookup('file', 'devops_ssh.pub') }}"
